# Generated by Django 3.2.13 on 2022-05-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Author name', max_length=150, unique=True),
        ),
    ]
